apiVersion: apps/v1
kind: Deployment
metadata:
  name: gogoconf-deployment
  labels:
    app: gogoconf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gogoconf
  template:
    metadata:
      labels:
        app: gogoconf
    spec:
      containers:
      - name: gogoconf
        image: agonzalezro/gogoconf:latest # Don't use latest at home!
        imagePullPolicy: Always
