apiVersion: v1
kind: Service
metadata:
  name: gogoconf-service-80
spec:
  type: LoadBalancer
  ports:
  - name: gogoconf-80
    port: 80
    targetPort: 8081
    protocol: TCP
  selector:
    app: gogoconf
